spring:
  application:
    name: twitter
  datasource:
    url: jdbc:mysql://localhost:3306/twitter?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: qwe123@@
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.mybatis: trace
    org.apache.ibatis: trace